### ISSUE TITLE
one more  issues for the bug in testcase_issues

### ISSUE THREAD

**Issue by venkateshmaryala** [venkateshmaryala/testcase_issues#2]
this is a kind of bug,,,  I am not able to fix these issues @venkateshnetenrich

- first check the code
- then login 
- try to fix it 

1. need stepts for login 
2. need 

> make sure to work on it

`<h1>My first PHP page</h1>v`

- [task1 ] 

- [task2 ] 

- [ task3 ]

 [https://www.w3schools.com/php/php_syntax.asp](url)'

 @venkateshnetenrich

#please check this comment

**Comment by venkateshnetenrich** [comment]
I have fixed the bug please check verify @venkateshmaryala 

> hope it is done

**Comment by venkateshnetenrich** [comment]
please make it to 

> enhanced the code

**Comment by venkateshmaryala** [comment]
ok @venkateshnetenrich
